### ISSUE TITLE
Consider supporting Carthage

### ISSUE THREAD

**Issue by DanielAsher** [parse-community/ParseUI-iOS#189]
`Carthage` is the light-weight dependency manager that is used by thousands of iOS developers and projects. I believe Carthage support would quickly be used by many developers to integrate Parse into their toolchain.

**Comment by z4r** [comment]
:+1:

**Comment by leoMehlig** [comment]
I think if you rename the .zip in the release to ParseUI.framework.zip Carthage should be able to download the zipped framework.

*"To offer prebuilt frameworks for a specific tag, the binaries for all supported platforms should be zipped up together into one archive, and that archive should be attached to a published Release corresponding to that tag. The attachment should include .framework in its name (e.g., ReactiveCocoa.framework.zip), to indicate to Carthage that it contains binaries."* - (from the [Carthage README.md](https://github.com/Carthage/Carthage))

This could be a nice workaround until ParseUI completely supports carthage

**Comment by nlutsenko** [comment]
Not as easy, though... That package has static frameworks compiled, whilst Carthage explicitly needs Dynamic frameworks to work.

**Comment by Bogidon** [comment]
@nlutsenko which package has static frameworks compiled? Can you give a brief overview of the work required to get this to work? I'd love to do it if I have time.

**Comment by Bogidon** [comment]
🤖 beep bop @nlutsenko

**Comment by Bogidon** [comment]
Nevermind... :sob: :sob: :sob:

**Comment by nlutsenko** [comment]
@Bogidon, still is going to happen, don't be worried.
I am still commited to supporting this and all the others projects here at Parse.

The package that we used to attach to releases has static framework compiled indeed.
The brief overview of the stuff that needs to be done:
- [ ] Create an actual ParseUI.xcodeproj with static framework
- [ ] Add static framework target to ParseUI.xcodeproj for ParseUI.framework
- [ ] Convert usage of Bolts/FBSDK/Parse and friends to use dynamic framework targets via Carthage
- [ ] Add dynamic framework target to ParseUI.xcodeproj for ParseUI.framework
- [ ] Add dynamic framework target to Travis-CI.

I am going to tackle these one-by-one, but we'll get there soon.

**Comment by Bogidon** [comment]
It's great to hear that Parse is still going to get development @nlutsenko! :dancer:

**Comment by iStopped** [comment]
:+1:

**Comment by lfarah** [comment]
👍

**Comment by reallyseth** [comment]
+1

**Comment by danstepanov** [comment]
👍

**Comment by DorianMartinez** [comment]
Any updates?

**Comment by danstepanov** [comment]
@nlutsenko any update on this?

**Comment by zirinisp** [comment]
Any updates?

**Comment by DanielAsher** [comment]
Should I close this?
