### ISSUE TITLE
PFImageView doesn't display the image in iOS 10 

### ISSUE THREAD

**Issue by szlangini** [parse-community/ParseUI-iOS#250]
See title.

Just upgraded my project to iOS10, downloaded all the latest SDKs in advance. 
PFImageView won't display it's data properly anymore.

**Comment by szlangini** [comment]
I have solved it. It is due to iOS10 creating UIImageViews and it's subclasses automatically as (0,0,1000,1000) before being resized. you need to call layoutIfNeeded() on your view before setting things like masksToBounds.

**Comment by jeffreyjackson** [comment]
can this issue be closed?
