### ISSUE TITLE
ParseUI has been deprecated in favor of Parse/UI ?

### ISSUE THREAD

**Issue by yingmu52** [parse-community/ParseUI-iOS#266]
After running `Pod install`, I get the following warnings 
`[!] ParseUI has been deprecated in favor of Parse/UI`
Is `ParseUI` going to be part of `ParseSDK`? Where should I get this pod properly?

**Comment by flovilmart** [comment]
It is part of the Parse SDK now, you can use the pod ‘Parse/UI’

**Comment by yingmu52** [comment]
So I just removed 
`pod 'ParseUI'` 
from my `Podfile` and just use
 `pod 'Parse'` 

I am not getting the  `PFQueryTableViewController`, any idea?

**Comment by flovilmart** [comment]
You have to add `pod ‘parse/UI’`

**Comment by yingmu52** [comment]
Changed `Podfile` 
```
   pod 'Parse'
   pod 'Parse/UI'
```

Now, I get this error 
```
[!] Unable to satisfy the following requirements:

- `Parse/UI` required by `Podfile`

Specs satisfying the `Parse/UI` dependency were found, but they required a higher minimum deployment target.
```

**Comment by flovilmart** [comment]
That means you either need to bump you minimum deployment target to the one that matches or stay on the current version which won't receive updates.

For reference, the minimum deployment target for Parse/UI is iOS 9 https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse.podspec#L146

**Comment by yingmu52** [comment]
Problem solved, this @flovilmart

**Comment by flovilmart** [comment]
No problem! We move all iOS sub projects into a mono repo to ensure a better support and a more consistent developer experience.
