### ISSUE TITLE
How to use Swift Decoder with PFUser/PFObjects?

### ISSUE THREAD

**Issue by farhansyed9** [parse-community/ParseUI-iOS#270]
I was wondering if it's possible for when I grab data from the server, which comes back as a PFObject, to use Swift's decodable feature. Or do I need to do some extra work for that to work. 
Thanks!

**Comment by flovilmart** [comment]
It’s not possible unless you use the REST api directly with URLSession.

**Comment by farhansyed9** [comment]
I see, thanks for the swift (lol) response!
