### ISSUE TITLE
'Parse/PFFile.h' file not found after Pod update

### ISSUE THREAD

**Issue by qunzorez** [parse-community/ParseUI-iOS#271]
Hello,
I have big issues, today i want to update POD's in my project.
I use **Parse/UI**, after pod update i got such error:

> 'Parse/PFFile.h' file not found

My podFile:
  ```
    pod 'Parse'
    pod 'Parse/UI'
```
I work with **Swift 4.2**

**Comment by flovilmart** [comment]
This project is archived, please check the IOS SDK monorepoz. As written in the README.
